-- MySQL Script generated by MySQL Workbench
-- Thu Oct 11 17:33:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`arbitros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`arbitros` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `carrera` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_ingreso` DATE NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`deportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`deportes` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `deporteid_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`divisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`divisiones` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `deporteid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `deporteid_idx` (`deporteid` ASC),
  CONSTRAINT `deporteid`
    FOREIGN KEY (`deporteid`)
    REFERENCES `proyecto`.`deportes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`equipos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `divisionid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `carrera` VARCHAR(120) NULL DEFAULT NULL,
  `facultad` VARCHAR(120) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `equipoid_UNIQUE` (`id` ASC),
  INDEX `divisionid_idx` (`divisionid` ASC),
  CONSTRAINT `divisionid`
    FOREIGN KEY (`divisionid`)
    REFERENCES `proyecto`.`divisiones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`lugares` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(120) NULL DEFAULT NULL,
  `capacidad` VARCHAR(45) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `lugarid_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`partidos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `equipo_1` INT(10) UNSIGNED NULL DEFAULT NULL,
  `equipo_2` INT(10) UNSIGNED NULL DEFAULT NULL,
  `divisionid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `lugarid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ganador` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` VARCHAR(45) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `empate` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `partidoid_UNIQUE` (`id` ASC),
  INDEX `lugar_idx` (`lugarid` ASC),
  INDEX `ganador_idx` (`ganador` ASC),
  INDEX `divisionid_idx` (`divisionid` ASC),
  INDEX `equipo1_idx` (`equipo_1` ASC),
  INDEX `equipo2_idx` (`equipo_2` ASC),
  CONSTRAINT `divisionid1`
    FOREIGN KEY (`divisionid`)
    REFERENCES `proyecto`.`divisiones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipo1`
    FOREIGN KEY (`equipo_1`)
    REFERENCES `proyecto`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `equipo2`
    FOREIGN KEY (`equipo_2`)
    REFERENCES `proyecto`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ganador`
    FOREIGN KEY (`ganador`)
    REFERENCES `proyecto`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lugarid`
    FOREIGN KEY (`lugarid`)
    REFERENCES `proyecto`.`lugares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`arbitrajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`arbitrajes` (
  `partidoid` INT(10) UNSIGNED NOT NULL,
  `arbitroid` INT(10) UNSIGNED NOT NULL,
  `tipo` VARCHAR(80) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`arbitroid`, `partidoid`),
  INDEX `partidoid_idx` (`partidoid` ASC),
  CONSTRAINT `arbitroid`
    FOREIGN KEY (`arbitroid`)
    REFERENCES `proyecto`.`arbitros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `partidoid`
    FOREIGN KEY (`partidoid`)
    REFERENCES `proyecto`.`partidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`campeonatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`campeonatos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `divisionid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `ano` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(120) NULL DEFAULT NULL,
  `semestre` VARCHAR(45) NULL DEFAULT NULL,
  `campeon` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_termino` DATE NULL DEFAULT NULL,
  `reglamento` VARCHAR(120) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ligaid_UNIQUE` (`id` ASC),
  INDEX `campeon_idx` (`campeon` ASC),
  INDEX `divisionid_idx` (`divisionid` ASC),
  CONSTRAINT `campeon`
    FOREIGN KEY (`campeon`)
    REFERENCES `proyecto`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `divisionid2`
    FOREIGN KEY (`divisionid`)
    REFERENCES `proyecto`.`divisiones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`data_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`data_types` (
  `id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name_singular` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name_plural` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `icon` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `model_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `policy_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `controller` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `generate_permissions` TINYINT(1) NOT NULL DEFAULT '0',
  `server_side` TINYINT(4) NOT NULL DEFAULT '0',
  `details` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `data_types_name_unique` (`name` ASC),
  UNIQUE INDEX `data_types_slug_unique` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`data_rows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`data_rows` (
  `id` INT(10) UNSIGNED NOT NULL,
  `data_type_id` INT(10) UNSIGNED NOT NULL,
  `field` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `required` TINYINT(1) NOT NULL DEFAULT '0',
  `browse` TINYINT(1) NOT NULL DEFAULT '1',
  `read` TINYINT(1) NOT NULL DEFAULT '1',
  `edit` TINYINT(1) NOT NULL DEFAULT '1',
  `add` TINYINT(1) NOT NULL DEFAULT '1',
  `delete` TINYINT(1) NOT NULL DEFAULT '1',
  `details` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `order` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `data_rows_data_type_id_foreign` (`data_type_id` ASC),
  CONSTRAINT `data_rows_data_type_id_foreign`
    FOREIGN KEY (`data_type_id`)
    REFERENCES `proyecto`.`data_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`noticias` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `deporteid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `texto` VARCHAR(2000) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `deporteid_idx` (`deporteid` ASC),
  CONSTRAINT `deporteid1`
    FOREIGN KEY (`deporteid`)
    REFERENCES `proyecto`.`deportes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`imagenes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `noticiaid` INT(10) UNSIGNED NOT NULL,
  `url` VARCHAR(150) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `noticiaid_idx` (`noticiaid` ASC),
  CONSTRAINT `noticiaid`
    FOREIGN KEY (`noticiaid`)
    REFERENCES `proyecto`.`noticias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`jugadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`jugadores` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `equipoid` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(160) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `ano_ingreso` INT(11) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `equipoid`),
  UNIQUE INDEX `jugadorid_UNIQUE` (`id` ASC),
  INDEX `equipoid_idx` (`equipoid` ASC),
  CONSTRAINT `equipoid`
    FOREIGN KEY (`equipoid`)
    REFERENCES `proyecto`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`menus` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_name_unique` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`menu_items` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menu_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `url` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `target` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT '_self',
  `icon_class` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `color` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `parent_id` INT(11) NULL DEFAULT NULL,
  `order` INT(11) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `route` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `parameters` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `menu_items_menu_id_foreign` (`menu_id` ASC),
  CONSTRAINT `menu_items_menu_id_foreign`
    FOREIGN KEY (`menu_id`)
    REFERENCES `proyecto`.`menus` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`pages` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `author_id` INT(11) NOT NULL,
  `title` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `excerpt` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `body` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `image` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `slug` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `meta_description` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `status` ENUM('ACTIVE', 'INACTIVE') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL DEFAULT 'INACTIVE',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `layout` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pages_slug_unique` (`slug` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`partido_jugadors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`partido_jugadors` (
  `partidoid` INT(10) UNSIGNED NOT NULL,
  `jugadorid` INT(10) UNSIGNED NOT NULL,
  `puntos` INT(11) NULL DEFAULT '0',
  `triples` INT(11) NULL DEFAULT '0',
  `amarilla` TINYINT(4) NULL DEFAULT '0',
  `roja` TINYINT(4) NULL DEFAULT '0',
  `faltas_b` INT(11) NULL DEFAULT '0' COMMENT 'faltas basquetball',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`partidoid`, `jugadorid`),
  INDEX `jugadorid_idx` (`jugadorid` ASC),
  CONSTRAINT `jugadorid1`
    FOREIGN KEY (`jugadorid`)
    REFERENCES `proyecto`.`jugadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `partidoid0`
    FOREIGN KEY (`partidoid`)
    REFERENCES `proyecto`.`partidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`password_resets` (
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`permissions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `table_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `permissions_key_index` (`key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_name_unique` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`permission_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`permission_role` (
  `permission_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`permission_id`, `role_id`),
  INDEX `permission_role_permission_id_index` (`permission_id` ASC),
  INDEX `permission_role_role_id_index` (`role_id` ASC),
  CONSTRAINT `permission_role_permission_id_foreign`
    FOREIGN KEY (`permission_id`)
    REFERENCES `proyecto`.`permissions` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `permission_role_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `proyecto`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`sanciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`sanciones` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `jugadorid` INT(10) UNSIGNED NOT NULL,
  `tiempo` VARCHAR(45) NULL DEFAULT NULL,
  `comentario` VARCHAR(200) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `jugadorid`),
  INDEX `jugadorid_idx` (`jugadorid` ASC),
  CONSTRAINT `jugadorid0`
    FOREIGN KEY (`jugadorid`)
    REFERENCES `proyecto`.`jugadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`settings` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `display_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `value` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `details` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `order` INT(11) NOT NULL DEFAULT '1',
  `group` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `settings_key_unique` (`key` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`usuarios` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NULL DEFAULT NULL,
  `correo` VARCHAR(200) NULL DEFAULT NULL,
  `password` VARCHAR(200) NULL DEFAULT NULL,
  `admin` TINYINT(4) NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`subscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`subscripciones` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuarioid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `equipoid` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuarioid_idx` (`usuarioid` ASC),
  INDEX `equipoid_idx` (`equipoid` ASC),
  CONSTRAINT `equipoid3`
    FOREIGN KEY (`equipoid`)
    REFERENCES `proyecto`.`equipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuarioid1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `proyecto`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `proyecto`.`translations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`translations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `column_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `foreign_key` INT(10) UNSIGNED NOT NULL,
  `locale` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `value` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `translations_table_name_column_name_foreign_key_locale_unique` (`table_name` ASC, `column_name` ASC, `foreign_key` ASC, `locale` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `avatar` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'users/default.png',
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `remember_token` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `settings` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `users_role_id_foreign` (`role_id` ASC),
  CONSTRAINT `users_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `proyecto`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyecto`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`user_roles` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `user_roles_user_id_index` (`user_id` ASC),
  INDEX `user_roles_role_id_index` (`role_id` ASC),
  CONSTRAINT `user_roles_role_id_foreign`
    FOREIGN KEY (`role_id`)
    REFERENCES `proyecto`.`roles` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_roles_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `proyecto`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
